// Generated by gencpp from file local_inn/pose_communication.msg
// DO NOT EDIT!


#ifndef LOCAL_INN_MESSAGE_POSE_COMMUNICATION_H
#define LOCAL_INN_MESSAGE_POSE_COMMUNICATION_H

#include <ros/service_traits.h>


#include <local_inn/pose_communicationRequest.h>
#include <local_inn/pose_communicationResponse.h>


namespace local_inn
{

struct pose_communication
{

typedef pose_communicationRequest Request;
typedef pose_communicationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct pose_communication
} // namespace local_inn


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::local_inn::pose_communication > {
  static const char* value()
  {
    return "5aa28f834219f856593a6cf0bb2c70d5";
  }

  static const char* value(const ::local_inn::pose_communication&) { return value(); }
};

template<>
struct DataType< ::local_inn::pose_communication > {
  static const char* value()
  {
    return "local_inn/pose_communication";
  }

  static const char* value(const ::local_inn::pose_communication&) { return value(); }
};


// service_traits::MD5Sum< ::local_inn::pose_communicationRequest> should match
// service_traits::MD5Sum< ::local_inn::pose_communication >
template<>
struct MD5Sum< ::local_inn::pose_communicationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::local_inn::pose_communication >::value();
  }
  static const char* value(const ::local_inn::pose_communicationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::local_inn::pose_communicationRequest> should match
// service_traits::DataType< ::local_inn::pose_communication >
template<>
struct DataType< ::local_inn::pose_communicationRequest>
{
  static const char* value()
  {
    return DataType< ::local_inn::pose_communication >::value();
  }
  static const char* value(const ::local_inn::pose_communicationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::local_inn::pose_communicationResponse> should match
// service_traits::MD5Sum< ::local_inn::pose_communication >
template<>
struct MD5Sum< ::local_inn::pose_communicationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::local_inn::pose_communication >::value();
  }
  static const char* value(const ::local_inn::pose_communicationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::local_inn::pose_communicationResponse> should match
// service_traits::DataType< ::local_inn::pose_communication >
template<>
struct DataType< ::local_inn::pose_communicationResponse>
{
  static const char* value()
  {
    return DataType< ::local_inn::pose_communication >::value();
  }
  static const char* value(const ::local_inn::pose_communicationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LOCAL_INN_MESSAGE_POSE_COMMUNICATION_H
