// Generated by gencpp from file local_inn/pose_communication_cameraResponse.msg
// DO NOT EDIT!


#ifndef LOCAL_INN_MESSAGE_POSE_COMMUNICATION_CAMERARESPONSE_H
#define LOCAL_INN_MESSAGE_POSE_COMMUNICATION_CAMERARESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace local_inn
{
template <class ContainerAllocator>
struct pose_communication_cameraResponse_
{
  typedef pose_communication_cameraResponse_<ContainerAllocator> Type;

  pose_communication_cameraResponse_()
    : pose()  {
      pose.assign(0.0);
  }
  pose_communication_cameraResponse_(const ContainerAllocator& _alloc)
    : pose()  {
  (void)_alloc;
      pose.assign(0.0);
  }



   typedef boost::array<float, 3>  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::local_inn::pose_communication_cameraResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::local_inn::pose_communication_cameraResponse_<ContainerAllocator> const> ConstPtr;

}; // struct pose_communication_cameraResponse_

typedef ::local_inn::pose_communication_cameraResponse_<std::allocator<void> > pose_communication_cameraResponse;

typedef boost::shared_ptr< ::local_inn::pose_communication_cameraResponse > pose_communication_cameraResponsePtr;
typedef boost::shared_ptr< ::local_inn::pose_communication_cameraResponse const> pose_communication_cameraResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::local_inn::pose_communication_cameraResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::local_inn::pose_communication_cameraResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::local_inn::pose_communication_cameraResponse_<ContainerAllocator1> & lhs, const ::local_inn::pose_communication_cameraResponse_<ContainerAllocator2> & rhs)
{
  return lhs.pose == rhs.pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::local_inn::pose_communication_cameraResponse_<ContainerAllocator1> & lhs, const ::local_inn::pose_communication_cameraResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace local_inn

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::local_inn::pose_communication_cameraResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::local_inn::pose_communication_cameraResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::local_inn::pose_communication_cameraResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::local_inn::pose_communication_cameraResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::local_inn::pose_communication_cameraResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::local_inn::pose_communication_cameraResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::local_inn::pose_communication_cameraResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5e7af384a7bc934f230231c255c5249e";
  }

  static const char* value(const ::local_inn::pose_communication_cameraResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5e7af384a7bc934fULL;
  static const uint64_t static_value2 = 0x230231c255c5249eULL;
};

template<class ContainerAllocator>
struct DataType< ::local_inn::pose_communication_cameraResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "local_inn/pose_communication_cameraResponse";
  }

  static const char* value(const ::local_inn::pose_communication_cameraResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::local_inn::pose_communication_cameraResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Response\n"
"float32[3] pose  # x, y, theta\n"
"\n"
"\n"
"\n"
;
  }

  static const char* value(const ::local_inn::pose_communication_cameraResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::local_inn::pose_communication_cameraResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pose_communication_cameraResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::local_inn::pose_communication_cameraResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::local_inn::pose_communication_cameraResponse_<ContainerAllocator>& v)
  {
    s << indent << "pose[]" << std::endl;
    for (size_t i = 0; i < v.pose.size(); ++i)
    {
      s << indent << "  pose[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.pose[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // LOCAL_INN_MESSAGE_POSE_COMMUNICATION_CAMERARESPONSE_H
