// Generated by gencpp from file local_inn/pose_communication_cameraRequest.msg
// DO NOT EDIT!


#ifndef LOCAL_INN_MESSAGE_POSE_COMMUNICATION_CAMERAREQUEST_H
#define LOCAL_INN_MESSAGE_POSE_COMMUNICATION_CAMERAREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace local_inn
{
template <class ContainerAllocator>
struct pose_communication_cameraRequest_
{
  typedef pose_communication_cameraRequest_<ContainerAllocator> Type;

  pose_communication_cameraRequest_()
    : image_data()  {
    }
  pose_communication_cameraRequest_(const ContainerAllocator& _alloc)
    : image_data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _image_data_type;
  _image_data_type image_data;





  typedef boost::shared_ptr< ::local_inn::pose_communication_cameraRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::local_inn::pose_communication_cameraRequest_<ContainerAllocator> const> ConstPtr;

}; // struct pose_communication_cameraRequest_

typedef ::local_inn::pose_communication_cameraRequest_<std::allocator<void> > pose_communication_cameraRequest;

typedef boost::shared_ptr< ::local_inn::pose_communication_cameraRequest > pose_communication_cameraRequestPtr;
typedef boost::shared_ptr< ::local_inn::pose_communication_cameraRequest const> pose_communication_cameraRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::local_inn::pose_communication_cameraRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::local_inn::pose_communication_cameraRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::local_inn::pose_communication_cameraRequest_<ContainerAllocator1> & lhs, const ::local_inn::pose_communication_cameraRequest_<ContainerAllocator2> & rhs)
{
  return lhs.image_data == rhs.image_data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::local_inn::pose_communication_cameraRequest_<ContainerAllocator1> & lhs, const ::local_inn::pose_communication_cameraRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace local_inn

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::local_inn::pose_communication_cameraRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::local_inn::pose_communication_cameraRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::local_inn::pose_communication_cameraRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::local_inn::pose_communication_cameraRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::local_inn::pose_communication_cameraRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::local_inn::pose_communication_cameraRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::local_inn::pose_communication_cameraRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1b1fb4ce4406affe0886a88095de24da";
  }

  static const char* value(const ::local_inn::pose_communication_cameraRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1b1fb4ce4406affeULL;
  static const uint64_t static_value2 = 0x0886a88095de24daULL;
};

template<class ContainerAllocator>
struct DataType< ::local_inn::pose_communication_cameraRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "local_inn/pose_communication_cameraRequest";
  }

  static const char* value(const ::local_inn::pose_communication_cameraRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::local_inn::pose_communication_cameraRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Request\n"
"float32[] image_data  # camera scan data but using only pose as of now (array of floats)\n"
"\n"
;
  }

  static const char* value(const ::local_inn::pose_communication_cameraRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::local_inn::pose_communication_cameraRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.image_data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pose_communication_cameraRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::local_inn::pose_communication_cameraRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::local_inn::pose_communication_cameraRequest_<ContainerAllocator>& v)
  {
    s << indent << "image_data[]" << std::endl;
    for (size_t i = 0; i < v.image_data.size(); ++i)
    {
      s << indent << "  image_data[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.image_data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // LOCAL_INN_MESSAGE_POSE_COMMUNICATION_CAMERAREQUEST_H
