// Generated by gencpp from file local_inn/pose_communication_camera.msg
// DO NOT EDIT!


#ifndef LOCAL_INN_MESSAGE_POSE_COMMUNICATION_CAMERA_H
#define LOCAL_INN_MESSAGE_POSE_COMMUNICATION_CAMERA_H

#include <ros/service_traits.h>


#include <local_inn/pose_communication_cameraRequest.h>
#include <local_inn/pose_communication_cameraResponse.h>


namespace local_inn
{

struct pose_communication_camera
{

typedef pose_communication_cameraRequest Request;
typedef pose_communication_cameraResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct pose_communication_camera
} // namespace local_inn


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::local_inn::pose_communication_camera > {
  static const char* value()
  {
    return "c4fc5fe5d8e49992c022543ae4cff221";
  }

  static const char* value(const ::local_inn::pose_communication_camera&) { return value(); }
};

template<>
struct DataType< ::local_inn::pose_communication_camera > {
  static const char* value()
  {
    return "local_inn/pose_communication_camera";
  }

  static const char* value(const ::local_inn::pose_communication_camera&) { return value(); }
};


// service_traits::MD5Sum< ::local_inn::pose_communication_cameraRequest> should match
// service_traits::MD5Sum< ::local_inn::pose_communication_camera >
template<>
struct MD5Sum< ::local_inn::pose_communication_cameraRequest>
{
  static const char* value()
  {
    return MD5Sum< ::local_inn::pose_communication_camera >::value();
  }
  static const char* value(const ::local_inn::pose_communication_cameraRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::local_inn::pose_communication_cameraRequest> should match
// service_traits::DataType< ::local_inn::pose_communication_camera >
template<>
struct DataType< ::local_inn::pose_communication_cameraRequest>
{
  static const char* value()
  {
    return DataType< ::local_inn::pose_communication_camera >::value();
  }
  static const char* value(const ::local_inn::pose_communication_cameraRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::local_inn::pose_communication_cameraResponse> should match
// service_traits::MD5Sum< ::local_inn::pose_communication_camera >
template<>
struct MD5Sum< ::local_inn::pose_communication_cameraResponse>
{
  static const char* value()
  {
    return MD5Sum< ::local_inn::pose_communication_camera >::value();
  }
  static const char* value(const ::local_inn::pose_communication_cameraResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::local_inn::pose_communication_cameraResponse> should match
// service_traits::DataType< ::local_inn::pose_communication_camera >
template<>
struct DataType< ::local_inn::pose_communication_cameraResponse>
{
  static const char* value()
  {
    return DataType< ::local_inn::pose_communication_camera >::value();
  }
  static const char* value(const ::local_inn::pose_communication_cameraResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LOCAL_INN_MESSAGE_POSE_COMMUNICATION_CAMERA_H
