(cl:defpackage local_inn-srv
  (:use )
  (:export
   "POSE_COMMUNICATION"
   "<POSE_COMMUNICATION-REQUEST>"
   "POSE_COMMUNICATION-REQUEST"
   "<POSE_COMMUNICATION-RESPONSE>"
   "POSE_COMMUNICATION-RESPONSE"
   "POSE_COMMUNICATION_CAMERA"
   "<POSE_COMMUNICATION_CAMERA-REQUEST>"
   "POSE_COMMUNICATION_CAMERA-REQUEST"
   "<POSE_COMMUNICATION_CAMERA-RESPONSE>"
   "POSE_COMMUNICATION_CAMERA-RESPONSE"
  ))

